spring:
  datasource:
    # Server MySQL locale (connessione IDE "BELLUM"), schema applicativo: boffalora
    url: jdbc:mysql://localhost:3306/boffalora
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: project

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: boffalora
        format_sql: true
        use_sql_comments: true

server:
  port: 8080